import { mkdir, readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";

const names = JSON.parse(
  await readFile("packages/contracts/schema/manifest.json", "utf8"),
);
const checking = process.argv.includes("--check");
const banner =
  "// Generated by pnpm contracts:generate. Edit the Python models.\n";
if (!checking) await mkdir("packages/contracts/generated", { recursive: true });
async function output(name, content) {
  const target = `packages/contracts/generated/${name}.d.ts`;
  if (checking) {
    const existing = (await readFile(target, "utf8")).replace(/\r\n/g, "\n");
    const expected = content.replace(/\r\n/g, "\n");
    if (existing !== expected) {
      throw new Error(
        `TypeScript contract drift in ${name}: run pnpm contracts:generate`,
      );
    }
  } else {
    await writeFile(target, content);
  }
}
for (const name of names) {
  const schema = JSON.parse(
    await readFile(`packages/contracts/schema/${name}.json`, "utf8"),
  );
  await output(
    name,
    banner +
      (await compile(schema, name, {
        bannerComment: "",
        additionalProperties: false,
      })),
  );
}
await output(
  "index",
  banner +
    names.map((name) => `export type { ${name} } from "./${name}";\n`).join(""),
);
console.log(
  checking
    ? "TypeScript contracts verified."
    : "TypeScript contracts generated.",
);
