export const workspaceCopy = {
  en: {
    processingLocation: "Process image on",
    serverMode: "Python server · recommended for phones",
    deviceMode: "On this device · works offline after assets load",
    serverPrivacy: "Preview stays here until you allow sending",
    serverRead: "Read text on the server",
    serverReading: "Your computer is reading the image…",
    serverOcrTask: "Reads printed text on the computer",
    serverEngineNote:
      "The computer runs Tesseract for English and Nepali. Your phone only previews the image and displays the draft.",
    serverNotice:
      "Images are sent only when you allow server processing. The Python reader holds images and text in memory; it does not save them. Drafts clear when you leave this view.",
    imagePermission: "Send this image to your Python server?",
    imagePermissionBody:
      "The original image, including any personal details, goes to the configured ArogyaAI server for transcription. This permission lasts one hour and can be revoked in Privacy. Each image is sent only when you press Read.",
    allowImage: "Allow and read image",
    notNow: "Not now",
    home: "Home",
    images: "Read an image",
    language: "Language & voice",
    languageTitle: "Translate or speak in Nepali",
    languageBody:
      "English, Nepali and Tamang drafts. Record, correct and listen to Nepali text.",
    translation: "Translates a short passage",
    transcription: "Writes a Nepali audio draft",
    speech: "Reads Nepali text aloud",
    translateDraft: "Translate this draft or selected text",
    selectShortPassage:
      "Select a passage of up to 600 characters in the draft, then try again.",
    translationSharing:
      "Only the text you choose moves to Language & voice. Server processing requires a separate permission.",
    engines: "Tools & models",
    ask: "Ask a question",
    medicines: "Medicines",
    library: "Library",
    privacy: "Privacy",
    preview: "Development preview",
    eyebrow: "YOUR HEALTH, ONE STEP AT A TIME",
    title: "Start with what’s in front of you.",
    introduction:
      "A label you can’t read. A medicine you want to understand. A health question that needs a reliable source. Choose where to begin.",
    imageTitle: "Make the small print readable.",
    imageBody:
      "Bring a photo of a printed label or document. Let your computer read the text, then compare it with the original.",
    imageAction: "Open image reader",
    imageTag: "IMAGE WORKSPACE",
    imagePrivacy: "Your photo stays in this browser",
    medicineTitle: "Look up a medicine",
    medicineBody:
      "Search a name against the reviewed catalog. Compare candidates before taking the next step.",
    libraryTitle: "Find a reliable source",
    libraryBody:
      "Browse reviewed questions and the evidence behind them. Check the source and its review date.",
    questionTitle: "Have a question?",
    questionBody:
      "Ask from the reviewed catalog. If the evidence is missing, we’ll say so.",
    open: "Open",
    sourceCount: "approved sources",
    pendingContent:
      "Reviewed content is still being prepared. Image reading is available independently.",
    deviceFirst: "Start on your device",
    deviceFirstBody:
      "Preview images on your phone. Your computer handles reading, translation and voice after you allow processing.",
    readerTitle: "Read an image",
    readerBody:
      "A space for your label, printed note, or prescription photo. Start by checking that the original is clear.",
    choose: "Choose an image",
    camera: "Take a photo",
    formats: "JPEG, PNG or WebP · up to 8 MB / 16 MP",
    dropTitle: "Bring the document into view",
    dropBody:
      "Keep the whole page visible, use even light, and avoid reflections. You can also drop an image here.",
    localNotice:
      "Images and drafts stay in memory and are cleared when you leave this view or refresh. Nothing is uploaded.",
    rotate: "Rotate 90°",
    remove: "Remove image",
    previewLabel: "Original image",
    photoAlt: "Selected document for transcription",
    engineLanguage: "Text language",
    english: "English",
    nepali: "नेपाली",
    mixed: "English + नेपाली",
    read: "Read text on this device",
    reading: "Reading the image",
    loading: "Loading the local reader",
    cancel: "Cancel reading",
    engineNote:
      "Tesseract.js · printed text only. Model assets are loaded from this app when you start; your photo never leaves the browser.",
    draftTitle: "Your transcription draft",
    draftBody:
      "Compare every line with the photo. Handwriting, medicine names, decimals, strengths and instructions can be wrong. This is unverified text, not medical guidance.",
    draftEmpty: "Read the image or type a transcription here…",
    draftLabel: "Editable unverified transcription",
    draftStatus: "UNVERIFIED TRANSCRIPTION",
    download: "Save text draft",
    saved: "Draft includes an unverified label.",
    modelTitle: "What’s doing the work?",
    modelBody:
      "Live observations from the configured worker. Installed, loaded and available are different states.",
    refresh: "Refresh status",
    refreshing: "Checking engines…",
    observed: "Last checked",
    unavailable:
      "Could not reach the backend. Image preview and local OCR are separate tools.",
    sources: "Reviewed sources",
    questions: "Reviewed questions (up to 200)",
    ready: "Available",
    busy: "Worker busy",
    unconfigured: "Not configured",
    offline: "Unavailable",
    loaded: "Loaded in memory",
    idle: "Installed · loads on demand",
    unknown: "Memory state unknown",
    selection: "Selects evidence sentences",
    routing: "Suggests the task",
    revision: "Pinned revision",
    allocation: "Reported model allocation",
    ocrTitle: "Browser image reader",
    ocrDetail:
      "English and Nepali printed text · starts on demand · worker released after each reading",
    boundary:
      "Model readiness does not make the catalog ready. Answers require approved sources; free-form medical generation remains disabled.",
    consentDetails: "How question sharing works",
    consentBefore: "Before you send a question",
    consentAfter: "Question sharing is enabled",
    sharingBody:
      "Your questions and relevant earlier dialogue go to the ArogyaAI API and its private AI worker. Sending an image requires separate permission.",
  },
  ne: {
    processingLocation: "तस्बिर कहाँ पढ्ने",
    serverMode: "Python सर्भर · फोनका लागि सिफारिस",
    deviceMode: "यही उपकरणमा · मोडेल लोड भएपछि अफलाइन",
    serverPrivacy: "पठाउने अनुमति नदिएसम्म तस्बिर यहीँ रहन्छ",
    serverRead: "सर्भरमा पाठ पढ्नुहोस्",
    serverReading: "कम्प्युटरले तस्बिर पढ्दै छ…",
    serverOcrTask: "कम्प्युटरमा छापिएको पाठ पढ्छ",
    serverEngineNote:
      "कम्प्युटरमा Tesseract ले अंग्रेजी र नेपाली पढ्छ। फोनले तस्बिर र पाठ मस्यौदा देखाउँछ।",
    serverNotice:
      "अनुमति दिएपछि मात्र तस्बिर सर्भरमा जान्छ। Python ले तस्बिर र पाठ मेमोरीमा राख्छ, फाइलमा सुरक्षित गर्दैन। यो पृष्ठ छोड्दा मस्यौदा हट्छ।",
    imagePermission: "यो तस्बिर आफ्नो Python सर्भरमा पठाउने?",
    imagePermissionBody:
      "व्यक्तिगत विवरणसहित मूल तस्बिर पाठ पढ्न आरोग्यएआई सर्भरमा जान्छ। अनुमति एक घण्टा रहन्छ र गोपनीयताबाट रद्द गर्न सकिन्छ। पढ्ने बटन थिचेपछि मात्र हरेक तस्बिर पठाइन्छ।",
    allowImage: "अनुमति दिएर तस्बिर पढ्नुहोस्",
    notNow: "अहिले होइन",
    home: "गृह",
    images: "तस्बिर पढ्नुहोस्",
    language: "भाषा र आवाज",
    languageTitle: "अनुवाद गर्नुहोस् वा नेपालीमा बोल्नुहोस्",
    languageBody: "अंग्रेजी, नेपाली र तामाङ मस्यौदा। नेपाली आवाज रेकर्ड, सुधार र सुनुवाइ।",
    translation: "छोटो पाठ अनुवाद गर्छ",
    transcription: "नेपाली आवाजको पाठ मस्यौदा लेख्छ",
    speech: "नेपाली पाठ पढेर सुनाउँछ",
    translateDraft: "यो मस्यौदा वा छानिएको पाठ अनुवाद गर्नुहोस्",
    selectShortPassage: "मस्यौदामा ६०० अक्षरसम्मको पाठ छानेर फेरि प्रयास गर्नुहोस्।",
    translationSharing:
      "छानेको पाठ मात्र भाषा र आवाजमा जान्छ। सर्भर प्रक्रियाका लागि छुट्टै अनुमति चाहिन्छ।",
    engines: "उपकरण र मोडेल",
    ask: "प्रश्न सोध्नुहोस्",
    medicines: "औषधि",
    library: "पुस्तकालय",
    privacy: "गोपनीयता",
    preview: "विकास पूर्वावलोकन",
    eyebrow: "स्वास्थ्य बुझ्ने पहिलो कदम",
    title: "तपाईंसँग भएको जानकारीबाट सुरु गरौँ।",
    introduction:
      "पढ्न गाह्रो भएको लेबल, बुझ्न चाहेको औषधि वा भरपर्दो स्रोत चाहिएको स्वास्थ्य प्रश्न। कहाँबाट सुरु गर्ने छान्नुहोस्।",
    imageTitle: "साना अक्षर पढ्न सजिलो बनाउनुहोस्।",
    imageBody:
      "छापिएको लेबल वा कागजको तस्बिर ल्याउनुहोस्। कम्प्युटरबाट पाठ पढ्नुहोस् र मूल तस्बिरसँग तुलना गर्नुहोस्।",
    imageAction: "तस्बिर पढ्ने उपकरण खोल्नुहोस्",
    imageTag: "तस्बिरको कार्यक्षेत्र",
    imagePrivacy: "तस्बिर यही ब्राउजरमा रहन्छ",
    medicineTitle: "औषधि खोज्नुहोस्",
    medicineBody:
      "समीक्षित सूचीमा नाम खोज्नुहोस्। अर्को कदम अघि सम्भावित नामहरू तुलना गर्नुहोस्।",
    libraryTitle: "भरपर्दो स्रोत खोज्नुहोस्",
    libraryBody: "समीक्षित प्रश्न र प्रमाण हेर्नुहोस्। स्रोत र समीक्षा मिति जाँच्नुहोस्।",
    questionTitle: "प्रश्न छ?",
    questionBody: "समीक्षित सूचीबाट सोध्नुहोस्। प्रमाण नभएमा हामी स्पष्ट बताउँछौँ।",
    open: "खोल्नुहोस्",
    sourceCount: "स्वीकृत स्रोत",
    pendingContent: "समीक्षित सामग्री तयार हुँदै छ। तस्बिर पढ्ने सुविधा छुट्टै उपलब्ध छ।",
    deviceFirst: "आफ्नै उपकरणबाट सुरु गर्नुहोस्",
    deviceFirstBody:
      "फोनमा तस्बिर हेर्नुहोस्। अनुमति दिएपछि कम्प्युटरले पाठ, अनुवाद र आवाजको काम गर्छ।",
    readerTitle: "तस्बिर पढ्नुहोस्",
    readerBody:
      "लेबल, छापिएको कागज वा प्रेस्क्रिप्सनको तस्बिरका लागि कार्यक्षेत्र। पहिले मूल तस्बिर स्पष्ट छ कि छैन हेर्नुहोस्।",
    choose: "तस्बिर छान्नुहोस्",
    camera: "तस्बिर खिच्नुहोस्",
    formats: "JPEG, PNG वा WebP · ८ MB / १६ MP सम्म",
    dropTitle: "कागजलाई स्पष्ट देखाउनुहोस्",
    dropBody:
      "पूरै पाना देखिने गरी उज्यालो ठाउँमा तस्बिर खिच्नुहोस्। यहाँ तस्बिर तानेर पनि राख्न सकिन्छ।",
    localNotice:
      "तस्बिर र मस्यौदा मेमोरीमा मात्र रहन्छन्। यो पृष्ठ छोड्दा वा रिफ्रेस गर्दा हट्छन्। सर्भरमा पठाइँदैन।",
    rotate: "९०° घुमाउनुहोस्",
    remove: "तस्बिर हटाउनुहोस्",
    previewLabel: "मूल तस्बिर",
    photoAlt: "पाठ उतार्न छानिएको कागजको तस्बिर",
    engineLanguage: "पाठको भाषा",
    english: "English",
    nepali: "नेपाली",
    mixed: "English + नेपाली",
    read: "यही उपकरणमा पाठ पढ्नुहोस्",
    reading: "तस्बिर पढिँदै छ",
    loading: "स्थानीय उपकरण लोड हुँदै छ",
    cancel: "पढ्न रोक्नुहोस्",
    engineNote:
      "Tesseract.js · छापिएको पाठका लागि मात्र। सुरु गर्दा मोडेल यही एपबाट लोड हुन्छ; तस्बिर ब्राउजरबाट बाहिर जाँदैन।",
    draftTitle: "तपाईंको पाठ मस्यौदा",
    draftBody:
      "हरेक लाइन तस्बिरसँग तुलना गर्नुहोस्। हस्तलेखन, औषधिको नाम, दशमलव, मात्रा र निर्देशन गलत हुन सक्छन्। यो अप्रमाणित पाठ हो, चिकित्सकीय सल्लाह होइन।",
    draftEmpty: "तस्बिर पढ्नुहोस् वा यहाँ पाठ लेख्नुहोस्…",
    draftLabel: "सम्पादन गर्न मिल्ने अप्रमाणित पाठ",
    draftStatus: "अप्रमाणित पाठ",
    download: "पाठ मस्यौदा सुरक्षित गर्नुहोस्",
    saved: "मस्यौदामा अप्रमाणित भनेर उल्लेख हुन्छ।",
    modelTitle: "कुन उपकरणले काम गर्दै छ?",
    modelBody:
      "जडान गरिएको वर्करको हालको अवस्था। स्थापना, मेमोरीमा लोड र उपलब्धता फरक अवस्था हुन्।",
    refresh: "अवस्था पुनः जाँच्नुहोस्",
    refreshing: "उपकरण जाँचिँदै छ…",
    observed: "पछिल्लो जाँच",
    unavailable: "ब्याकएन्डमा जडान हुन सकेन। तस्बिर हेर्ने र स्थानीय OCR छुट्टै उपकरण हुन्।",
    sources: "समीक्षित स्रोत",
    questions: "समीक्षित प्रश्न (२०० सम्म)",
    ready: "उपलब्ध",
    busy: "वर्कर व्यस्त",
    unconfigured: "सेटअप भएको छैन",
    offline: "अनुपलब्ध",
    loaded: "मेमोरीमा लोड छ",
    idle: "स्थापित · आवश्यक पर्दा लोड हुन्छ",
    unknown: "मेमोरीको अवस्था अज्ञात",
    selection: "प्रमाणका वाक्य छान्छ",
    routing: "कार्यको सुझाव दिन्छ",
    revision: "निश्चित संस्करण",
    allocation: "मोडेलले जनाएको मेमोरी",
    ocrTitle: "ब्राउजरको तस्बिर पढ्ने उपकरण",
    ocrDetail:
      "अंग्रेजी र नेपाली छापिएको पाठ · आवश्यक पर्दा सुरु हुन्छ · हरेक पटक पढेपछि वर्कर हटाइन्छ",
    boundary:
      "मोडेल उपलब्ध हुँदैमा स्रोत सूची तयार हुँदैन। उत्तरका लागि स्वीकृत स्रोत चाहिन्छ; खुला चिकित्सकीय उत्तर बनाउने सुविधा बन्द छ।",
    consentDetails: "प्रश्न साझा गर्ने तरिका",
    consentBefore: "प्रश्न पठाउनुअघि",
    consentAfter: "प्रश्न साझा गर्ने अनुमति सक्रिय छ",
    sharingBody:
      "प्रश्नको पाठ मात्र आरोग्यएआई API र यसको निजी AI वर्करमा जान्छ। तस्बिर पठाउन छुट्टै अनुमति चाहिन्छ।",
  },
};
